FROM alpine:%%ALPINE_VERSION%%

ARG PKG_REPOSITORY %%PKG_REPOSITORY%%
ARG PKG_PUBKEY_URL %%PKG_PUBKEY_URL%%

RUN wget ${PKG_PUBKEY_URL} -P /etc/apk/keys \
    && apk add --no-cache --repository ${PKG_REPOSITORY} %%TOOL_NAME%%

COPY docker-entrypoint.sh /usr/local/bin
ENTRYPOINT ["docker-entrypoint.sh"]

