FROM alpine:%%ALPINE_VERSION%%

ARG PKG_REPOSITORY %%PKG_REPOSITORY%%
ARG PKG_PUBKEY_URL %%PKG_PUBKEY_URL%%
ARG PKG_PUBKEY %%PKG_PUBKEY%%

RUN wget ${PKG_PUBKEY_URL} -O /etc/apk/keys/${PKG_PUBKEY} \
    && apk add --no-cache --repository ${PKG_REPOSITORY} %%TOOL_NAME%% \
    && rm /etc/apk/keys/${PKG_PUBKEY}

