
FIND_LIBRARY(FMT_LIBRARY fmt)
FIND_PATH(FMT_INCLUDE_PATH fmt/format.h)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Fmt DEFAULT_MSG FMT_LIBRARY FMT_INCLUDE_PATH)

MARK_AS_ADVANCED(FMT_INCLUDE_PATH FMT_LIBRARY)
